### ISSUE TITLE
灰度发布是不是不能用

### ISSUE THREAD

**Issue by ciweigg2** [matevip/matecloud#1]
gray那个模块是不是没写完 好像是用不了的

**Comment by mateaix** [comment]
目前只是基于简单实现，完整方案正在优化中，敬请期待

**Comment by ytsafe** [comment]
你好，启动了uaa服务，getway服务， 调用接口mate-uaa/oauth/token 接口返回这个信息，是什么原因？“ callback({msg: '规则检测已经完成，可以正常上网！', state: 1}) ”

**Comment by mateaix** [comment]
已经支持并可以使用
