### ISSUE TITLE
MyBatis-Plus自动填充功能

### ISSUE THREAD

**Issue by vrchary** [matevip/matecloud#17]
看作者在mate-starter-database模块中用的mybatis-plus版本为3.4.0， 使用自带的handler处理createTime填充时，插入一直为null, 使用旧版的strictInsertFill()才好用，是怎么回事？ 下面解释掉的两种方试都不管用

       /*this.strictUpdateFill(metaObject, "createTime", LocalDateTime.class, LocalDateTime.now());
        this.strictUpdateFill(metaObject, "updateTime", LocalDateTime.class, LocalDateTime.now());*/

        /*this.strictUpdateFill(metaObject, "createTime", () -> LocalDateTime.now(), LocalDateTime.class);
        this.strictUpdateFill(metaObject, "updateTime", () -> LocalDateTime.now(), LocalDateTime.class);*/

        log.info("start insert fill ....");
        this.strictInsertFill(metaObject, "createTime", LocalDateTime.class, LocalDateTime.now());
        this.strictInsertFill(metaObject, "updateTime", LocalDateTime.class, LocalDateTime.now());

**Comment by mateaix** [comment]
官方样例：https://gitee.com/baomidou/mybatis-plus-samples/blob/master/mybatis-plus-sample-auto-fill-metainfo/src/main/java/com/baomidou/samples/metainfo/handler/MyMetaObjectHandler.java
