### ISSUE TITLE
演示项目中点击菜单中字典，报错500

### ISSUE THREAD

**Issue by wslzs** [matevip/matecloud#42]
![image](https://user-images.githubusercontent.com/35302223/129701145-4720930b-5d54-48a6-a0f5-c00a0290091a.png)
![image](https://user-images.githubusercontent.com/35302223/129701333-aaa6c196-68a1-436c-84f7-edba81feacb8.png)

**Comment by wslzs** [comment]
应该是前端少传了个code字段

**Comment by mateaix** [comment]
已解决
